### PR TITLE
feat: Using Cassandra user defined types from schema metadata test

### PR DESCRIPTION
**Pull request by Canhassi12**

### CODE REVIEW

**Comment by danielhe4rt** [comment]
Tried to rerun the tests a few times but I didn't have success on that. Maybe it can be a real issue on the driver. 

cc: @malusev998

**Comment by PedroPMS** [comment]
> Tried to rerun the tests a few times but I didn't have success on that. Maybe it can be a real issue on the driver.
> 
> cc: @malusev998

now it passed, I just rerun the job

**Comment by Canhassi12** [comment]
nice nice.

**Comment by CodeLieutenant** [comment]
Yes, found the problem in the driver, it segfaults from time to time, and the fix is in #54 pull request, which will be merged in the next couple of days

**Review by CodeLieutenant — CHANGES_REQUESTED** [review]
Just remove `tests-old/features/user_defined_types.feature` as that file is no longer needed

**Review by CodeLieutenant — APPROVED** [review]

**Comment by CodeLieutenant** [comment]
Thanks for the effort. Good Job

**Pull request merged**
