### PR TITLE
Refactor Collection

### PR DESCRIPTION
**Pull request by CodeLieutenant**
Refactor Cassandra/ScyllaDB Collection to Stub generated

### CODE REVIEW

**Review by danielhe4rt — APPROVED** [review]

**Comment by danielhe4rt** [comment]
Understood 10% but LGTM!

**Comment by danielhe4rt** [comment]
Hey @malusev998. Just wondering, what is the status of this PR?

**Comment by CodeLieutenant** [comment]
> Hey @malusev998. Just wondering, what is the status of this PR?

This is the most significant piece in the whole driver, it's going well for now, but there are many things to be done. Pretty much all complex types in the driver are based on the Collections API, doing them right and removing memory leaks from them (also doing some optimizations) will benefit the future releases

**Comment by CodeLieutenant** [comment]
This is going to be closed, no further development on this. We will be focusing our time on v2 branch and rewrite in rust

**Pull request closed without merging**
