### PR TITLE
Remove php build system in favour of CMake

### LINKED ISSUE #11: Add ScyllaDB support
While Cassandra is currently used a lot, for some heavy loads, ScyllaDB provides better performance and some exclusive features which are not present in current cpp-driver.

We should allow building with [ScyllaDB](https://github.com/scylladb/cpp-driver) fork of CPP-Driver.

When building php driver, this should be option in build script when linking

### LINKED ISSUE #14: Better IDE support
Add Cmake to the project, many of the popular IDEs support cmake based projects.
So this will be useful in the long run for maintaining the PHP Cassandra Driver.

### LINKED ISSUE #19: Staticly link LibCassandra and LibUV
Currently PHP Build system links libcassandra and libuv dynamically. this makes library slower on load, and distribution of the php extension more difficult. 

By replacing PHP Build system with CMake, we can statically link libuv and libcassandra.
Static linking should be default, but option could be provided in CMake to link dynamically.

### LINKED ISSUE #20: Remove PHPIZE from CMake
Currently phpize and autotools generate config.h file, this should be changed to CMake configure_file() function.

### PR DESCRIPTION
**Pull request by CodeLieutenant**
PHP's build system is old and clunky, this pull request removes it from the source tree and replaces it with more robust Cmake. Extension folder is deleted and all of it's content has been moved to root directory as it is the convention for extensions.

DataStax cpp-driver has been replaces with maintained [ScyllaDB](https://github.com/scylladb/cpp-driver) fork for now. When [Rust Version](https://github.com/scylladb/cpp-rust-driver) becomes stable, it will be replaces with that one.

Closes #14 #19 #11

### CODE REVIEW

**Comment by danielhe4rt** [comment]
Still in progress? Want to talk about this?

**Comment by CodeLieutenant** [comment]
> Still in progress? Want to talk about this?

This is still a draft, but it's near complete, it needs a little bit more testing. This pull request makes building and maintaining the library a lot easier, and allows for good IDE support.
This is the first pull request that supports ScyllaDB officially, and puts Apache Cassandra as second tier support

**Comment by danielhe4rt** [comment]
Just remember to list this command somewhere else. Can be here or directly on the readme and I'll figure out where to put it.

**Comment by CodeLieutenant** [comment]
I'll update Dockerfile so you can grab it from there

**Pull request merged**
